### ISSUE TITLE
npm ERR! Failed at the fs-ext@0.6.0 install script.

### ISSUE THREAD

**Issue by Metalexmfg** [mtconnect/mtconnect-agent#51]
npm ERR! Failed at the fs-ext@0.6.0 install script.

Anyone else seen this when installing on a Window's machine? I need a solution? Thanks.

Log..

..\fs-ext.cc(195): error C3861: 'fcntl': identifier not found [C:\Users\MURPHYJ\Documents\GitHub\mtconnect-agent\node_modules\fs-ext\build\fs-ext.vcxproj]
..\fs-ext.cc(374): error C3861: 'fcntl': identifier not found [C:\Users\MURPHYJ\Documents\GitHub\mtconnect-agent\node_modules\fs-ext\build\fs-ext.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\MURPHYJ\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\MURPHYJ\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\Users\MURPHYJ\Documents\GitHub\mtconnect-agent\node_modules\fs-ext
gyp ERR! node -v v6.10.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fs-ext@0.6.0 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fs-ext@0.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MURPHYJ\AppData\Roaming\npm-cache\_logs\2018-02-08T14_09_08_813Z-debug.log

**Comment by OvidiuBRO** [comment]
hello, I have a similar problem. I can't accomplish the DEPENDENCIES for windows from the read.me.

Thank you!

**Comment by Oen1997** [comment]
Same here :(

**Comment by wsobel** [comment]
I’m going to remove the project. It was a work in progress and we have switched back to the c++ agent as a new direction since there was more community support for the old source base. 

I’ll remove the repo. Sorry about the confusion. 

If there is interest in developing a node version of the agent. Please indicate your desire to keep this alive and who will contribute. 

Thanks and happy new year!
Will

(Sent from mobile)

**Comment by intolerance** [comment]
@wsobel, 

We're definitely interested in a Node version of the Agent. However, we would more than likely want to port it over to TypeScript. I will fork this repo for now until we can put some time in to it.

Additionally, do you plan on taking the `application/json` feature over to the C++ Agent in the meantime?

**Comment by GarySkills** [comment]
I actually put a developer on this for a while. I was trying to integrate it into NodeRed so I could include it with a Beaglebone/Arduino IoT (beagleduino) device i had built. We got the agent to run but had some trouble making the nodes communicate within the NodeRed interface. I was going to have some NodeRed developers look at it. I sat on it for a while because i got tied up with other projects but i was really hoping to get it to work with my device. It would have been nice to include it as a selling point. I'm getting back on the project this year. I also got the C++ agent to work but was trying to stay ahead of the curve since it was a new product.

**Comment by wsobel** [comment]
application/json is the next refactor planned for the c++ agent based on the accepts header field. If you have opinions on that as well, I’d be interested in stylistically which encoding you believe is best, attribute encoding, element order, etc...

We are planning on porting a lot of the key features to C++ like discovery and I’d generation for meta model merging.   

Thanks,
W

(Sent from mobile)
